"""add notified_user to intake_logs

Revision ID: 040538433124
Revises: 679966472abd
Create Date: 2026-07-18 20:50:07.319285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '040538433124'
down_revision: Union[str, None] = '679966472abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_link_tokens_token'), table_name='contact_link_tokens')
    op.drop_table('contact_link_tokens')
    op.drop_table('family_contacts')
    op.add_column('intake_logs', sa.Column('notified_user', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('medications', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('intake_logs', 'notified_user')
    op.create_table('family_contacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('family_contacts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('family_contacts_pkey'))
    )
    op.create_table('contact_link_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('contact_link_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_link_tokens_pkey'))
    )
    op.create_index(op.f('ix_contact_link_tokens_token'), 'contact_link_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
